# Generated by Django 4.2.16 on 2026-05-14 01:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'study_sessions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeakTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'weak_topics',
                'ordering': ['-error_count'],
            },
        ),
    ]
