# Generated by Django 4.2.16 on 2026-05-14 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('note_type', models.CharField(choices=[('summary', 'Summary'), ('detailed', 'Detailed'), ('revision', 'Revision'), ('bullet', 'Bullet Points')], default='summary', max_length=20)),
                ('source_type', models.CharField(choices=[('topic', 'Topic Input'), ('pdf', 'PDF Upload'), ('image', 'Image Upload'), ('text', 'Text Input')], default='topic', max_length=20)),
                ('raw_content', models.TextField(blank=True)),
                ('generated_content', models.TextField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'note_views',
                'unique_together': {('note', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-created_at'], name='notes_user_id_e4f281_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'subject'], name='notes_user_id_7eacdf_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_favorite'], name='notes_user_id_d415b3_idx'),
        ),
    ]
